config/routes.rb
Rails.application.routes.draw do
  root to: 'books#index'
  resources :books
  resources :rentals

  get '/users', to: 'users#index'
  get '/users/new', to: 'users#new', as: 'new_user'
  post '/users', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'user'
  get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  put '/users/:id', to: 'users#update'
  patch '/users/:id', to: 'users#update_in_office'
  delete '/users/:id', to: 'users#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
  # 本のタイトルのユニーク制約の設定について
  # 同じ本が２冊以上ある場合、１冊づつ別々で登録するためユニーク制約は設定しない
  validates :title, presence: true
  validates :title, length: { maximum: 30 }
  validate :validate_image

  has_many :rentals, dependent: :destroy
  has_one_attached :image

  def going_rental
    rentals.where(returned_at: nil).first
  end

  def current_borrower
    going_rental.user
  end

  def validate_image
    return unless image.attached?
    if image.blob.byte_size > 10.megabytes
      self.image = nil
      errors.add(:image, 'ファイルのサイズが大きすぎます')
    elsif !image?
      self.image = nil
      errors.add(:image, 'ファイルが対応している画像データではありません')
    end
  end

  private

  def image?
    %w[image/jpg image/jpeg image/gif image/png].include?(image.blob.content_type)
  end
end

app/models/rental.rb
# frozen_string_literal: true

class Rental < ApplicationRecord
  validate :not_rentable_as_rental_going, on: :create

  belongs_to :user
  belongs_to :book

  def going?
    returned_at.nil?
  end

  private

  def not_rentable_as_rental_going
    errors.add(book.title, 'は貸出中です。借りることはできません。') if book.going_rental
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  validates :name, presence: true
  validates :name, length: { maximum: 30 }
  validates :furigana, presence: true
  validates :furigana, length: { maximum: 30 }

  has_many :rentals, dependent: :nullify

  def renting_book
    rentals.where(returned_at: nil).last&.book
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  before_action :set_book, only: %i[show edit update destroy]

  def index
    @q = Book.ransack(params[:q])
    @books = @q.result.order(:title)
  end

  def show
    @rentals = @book.rentals.order(created_at: :desc)
  end

  def new
    @book = Book.new
  end

  def edit; end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to @book, notice: "書籍「#{@book.title}」を登録しました。"
    else
      render :new
    end
  end

  def destroy
    @book.destroy
    redirect_to books_url, notice: "書籍「#{@book.title}」を削除しました。"
  end

  def update
    if @book.update(book_params)
      redirect_to @book, notice: "書籍「#{@book.title}」の登録情報を更新しました。"
    else
      render :edit
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :image)
  end

  def set_book
    @book = Book.find(params[:id])
  end
end

app/controllers/rentals_controller.rb
# frozen_string_literal: true

class RentalsController < ApplicationController
  def index; end

  def new
    @rental = Renatl.new
  end

  def edit; end

  def create
    @book = Book.find(params[:book_id])
    @rental = Rental.new(rental_params)

    if @rental.save
      redirect_to @book, notice: "書籍「#{@book.title}」を借りました。"
    else
      @rentals = @book.rentals.order(created_at: :desc)
      render template: 'books/show'
    end
  end

  def update
    @book = Book.find(params[:book_id])
    @rental = @book.going_rental

    if @rental
      @rental.update(returned_at: Time.current)
      redirect_to @book, notice: "書籍「#{@book.title}」を返却しました。"
    else
      redirect_to @book, alert: "書籍「#{@book.title}」をまだ借りていないので返却できません"
    end
  end

  private

  def rental_params
    params.permit(:user_id, :book_id)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update update_in_office destroy]
  def index
    @users = User.all.order(:furigana)
  end

  def show
    @rentals = @user.rentals.order(created_at: :desc)
  end

  def new
    @user = User.new
  end

  def edit; end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to users_url, notice: "「#{@user.name}」を登録しました。"
    else
      render :new
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: "「#{@user.name}」を削除しました。"
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: "「#{@user.name}」の登録情報を更新しました。"
    else
      render :edit
    end
  end

  def update_in_office
    if @user.update(params.permit(:in_office))
      redirect_to @user, notice: "「#{@user.name}」の登録情報を更新しました。"
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :furigana)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/books/_form.html.slim
- if book.errors.present?
  ul#error_explanation.alert.alert-danger [style="list-style: none;"]
    - book.errors.full_messages.each do |message|
      li= message

= form_with model: book, local: true do |f|
    .mb-3
      = f.label :title
      .row
        .col-6
          = f.text_field :title, class: 'form-control mb-3 shadow-sm', id: 'title', placeholder: '書籍のタイトルを入力してください'
      = f.label :image
      .row
        .col-6
          = f.file_field :image, class: 'form-control shadow-sm'
    = f.submit nil, class: 'btn btn-primary shadow-sm'

app/views/books/edit.html.slim
.clearfix
  svg.bi.bi-book.float-start.me-3[xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" viewbox="0 0 16 16"]
    path[d="M1 2.828c.885-.37 2.154-.769 3.388-.893 1.33-.134 2.458.063 3.112.752v9.746c-.935-.53-2.12-.603-3.213-.493-1.18.12-2.37.461-3.287.811V2.828zm7.5-.141c.654-.689 1.782-.886 3.112-.752 1.234.124 2.503.523 3.388.893v9.923c-.918-.35-2.107-.692-3.287-.81-1.094-.111-2.278-.039-3.213.492V2.687zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783z"]
  h1 書籍の編集

= render partial: 'form', locals: { book: @book }

app/views/books/index.html.slim
= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'

.clearfix
  svg.bi.bi-book.float-start.me-3[xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" viewbox="0 0 16 16"]
    path[d="M1 2.828c.885-.37 2.154-.769 3.388-.893 1.33-.134 2.458.063 3.112.752v9.746c-.935-.53-2.12-.603-3.213-.493-1.18.12-2.37.461-3.287.811V2.828zm7.5-.141c.654-.689 1.782-.886 3.112-.752 1.234.124 2.503.523 3.388.893v9.923c-.918-.35-2.107-.692-3.287-.81-1.094-.111-2.278-.039-3.213.492V2.687zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783z"]
  h1 書籍一覧

= search_form_for @q, class: 'mb-5' do |f|
  = f.label :title_cont, '書籍検索', class: 'col-sm-2 col-form-label'
  .row
    .col-6
      = f.search_field :title_cont, class: 'form-control shadow-sm', placeholder: '書籍のタイトルを入力してください'
    .col-1
      = f.submit class: 'btn btn-primary shadow-sm'

.row.row-cols-2.row-cols-lg-3.g-4
  - @books.each do |book|
    .col
      .card.mb-3.shadow
        .row.g-0
          .col-3.ms-2.d-flex.align-items-center[style="height: 150px;"]
            - if book.image.attached?
              = image_tag book.image.variant(resize:'105x150').processed, class: 'img-thumbnail', alt: "書籍#{book.title}の画像"
            - else
              img.img-thumbnail[src="https://placehold.jp/257x364.png?text=book image" alt="書籍の画像（未登録のため代替のプレースホルダー画像）"]
          .col-8
            .card-body [style="height: 100%; display: flex; flex-direction: column; justify-content: space-between;"]
              h5.card-title
                a.stretched-link[href= book_path(book)]
                  = book.title
              p.card-text= "#{book.current_borrower.name}さんが借りています" if book.going_rental

app/views/books/new.html.slim
.clearfix
  svg.bi.bi-book.float-start.me-3[xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" viewbox="0 0 16 16"]
    path[d="M1 2.828c.885-.37 2.154-.769 3.388-.893 1.33-.134 2.458.063 3.112.752v9.746c-.935-.53-2.12-.603-3.213-.493-1.18.12-2.37.461-3.287.811V2.828zm7.5-.141c.654-.689 1.782-.886 3.112-.752 1.234.124 2.503.523 3.388.893v9.923c-.918-.35-2.107-.692-3.287-.81-1.094-.111-2.278-.039-3.213.492V2.687zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783z"]
  h1 書籍の新規登録

= render partial: 'form', locals: { book: @book }

app/views/books/show.html.slim
.clearfix.mb-3
  svg.bi.bi-book.float-start.me-3[xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" viewbox="0 0 16 16"]
    path[d="M1 2.828c.885-.37 2.154-.769 3.388-.893 1.33-.134 2.458.063 3.112.752v9.746c-.935-.53-2.12-.603-3.213-.493-1.18.12-2.37.461-3.287.811V2.828zm7.5-.141c.654-.689 1.782-.886 3.112-.752 1.234.124 2.503.523 3.388.893v9.923c-.918-.35-2.107-.692-3.287-.81-1.094-.111-2.278-.039-3.213.492V2.687zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783z"]
  h1.float-start = @book.title
  = link_to '編集', edit_book_path(@book), class: 'btn btn-link btn-lg ms-4'

.row
  .col-2
    - if @book.image.attached?
      = image_tag @book.image.variant(resize:'257x364').processed, class: 'img-thumbnail float-start shadow', alt: "書籍#{@book.title}の画像"
    - else
      img.img-thumbnail[src="https://placehold.jp/257x364.png?text=book image" alt="書籍#{@book.title}の画像（未登録のため代替のプレースホルダー画像）"]
  .col-10
    - if @rental&.errors.present?
      ul#error_explanation.alert.alert-danger [style="list-style: none;"]
        - @rental.errors.full_messages.each do |message|
          li= message

    - unless @book.going_rental
      = form_with url: rentals_path(book_id: @book.id), method: :post do |f|
        .row
          .col-6
            = f.collection_select(:user_id, User.where(in_office: true).order(:furigana), :id, :name, {prompt: '借りる人を選択してください'}, {class: 'form-control form-control-lg input-sm mb-3 shadow-sm'})
          .col-1
            = f.submit '借りる', class: 'btn btn-primary btn-lg mb-3 shadow-sm'
    - else
      = form_with url: rental_path(book_id: @book.id), method: :patch do |f|
        = f.submit '返す', class: 'btn btn-success btn-lg mb-3 shadow-sm'

h2.mt-3 貸し出し履歴

table.table.table-hover
  thead.thead-default
    tr
      th= User.human_attribute_name(:name)
      th= Rental.human_attribute_name(:created_at)
      th= Rental.human_attribute_name(:returned_at)
  tbody
    - @rentals.each do |rental|
      tr
        td= link_to rental.user.name, user_path(rental.user)
        td= I18n.l(rental.created_at)
        - if rental.going?
          td= '貸し出し中'
        -else
          td= I18n.l(rental.returned_at)

= link_to 'この書籍を削除する', @book, method: :delete, data: { confirm: "書籍「#{@book.title}」を削除します。よろしいですか？"}, class: 'btn btn-danger btn-lg col-3 my-5 shadow-sm'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Booksmanager
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .app-title.navbar.navbar-expand-sm.navbar-dark.bg-dark.mb-5
      .container.px-4
        = link_to 'Booksmanager', books_path, class: 'navbar-brand'
        .collapse.navbar-collapse
          ul.navbar-nav.me-auto.mb-2.mb-sm-0
            li.nav-item
              = link_to '書籍登録', new_book_path, class: 'nav-link'
            li.nav-item
              = link_to '社員一覧', users_path, class: 'nav-link'
            li.nav-item
              = link_to '社員登録', new_user_path, class: 'nav-link'

    .container.px-4
      -if flash.notice.present?
        .alert.alert-success= flash.notice
      - if flash.alert.present?
        .alert.alert-danger= flash.alert
      = yield

app/views/shared/_book_form.html.slim
- if book.errors.present?
  ul#error_explanation
    - book.errors.full_messages.each do |message|
      li= message

= form_with model: book, local: true do |f|
    .mb-3
      = f.label :title
      = f.text_field :title, class: 'form-control', id: 'title'
    = f.submit nil, class: 'btn btn-primary'

app/views/shared/_link.html.slim
.nav.justify-content-end
  = link_to '書籍一覧', books_path, class: 'nav-link'

app/views/shared/_user_form.html.slim
= form_with model: user, local: true do |f|
    .mb-3
      = f.label :name
      = f.text_field :name, class: 'form-control', id: 'name'
    = f.submit nil, class: 'btn btn-primary'

app/views/users/_form.html.slim
- if user.errors.present?
  ul#error_explanation.alert.alert-danger [style="list-style: none;"]
    - user.errors.full_messages.each do |message|
      li= message

= form_with model: user, method: user.persisted? ? :put : :post, local: true do |f|
    .mb-3
      = f.label :name
      .row
        .col-6
          = f.text_field :name, class: 'form-control mb-3 shadow-sm', id: 'name', placeholder: '社員名を入力してください'
      = f.label :furigana
      .row
        .col-6
          = f.text_field :furigana, class: 'form-control shadow-sm', id: 'furigana', placeholder: 'フリガナをカタカナで入力してください'
    = f.submit nil, class: 'btn btn-primary shadow-sm'

app/views/users/edit.html.slim
.clearfix
  svg.bi.bi-person.float-start.me-3[xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" viewBox="0 0 16 16"]
    path.[d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"]
  h1 社員情報の編集

= render partial: 'form', locals: { user: @user }

app/views/users/index.html.slim
.clearfix
  svg.bi.bi-person.float-start.me-3[xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" viewBox="0 0 16 16"]
    path.[d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"]
  h1 社員一覧

table.table.table-hover
  thead.thead-default
    tr
      th= User.human_attribute_name(:name)
      th= '借りている書籍'
  tbody
    - @users.each do |user|
      tr
        td= link_to user.name, user
        - if user.renting_book
          td= link_to user.renting_book.title, book_path(user.renting_book)
        - else
          td
        - unless user.in_office?
          td.text-danger= '退職済み'
        - else
          td

app/views/users/new.html.slim
.clearfix
  svg.bi.bi-person.float-start.me-3[xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" viewBox="0 0 16 16"]
    path.[d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"]
  h1 社員登録

= render partial: 'form', locals: { user: @user }

app/views/users/show.html.slim
- unless @user.in_office
  h4.text-danger 退職済み

.clearfix
  - if @user.in_office?
    svg.bi.bi-person.float-start.me-3[xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" viewBox="0 0 16 16"]
      path.[d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"]
    h1.float-start= @user.name
  - else
    .text-secondary
      svg.bi.bi-person.float-start.me-3[xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" viewBox="0 0 16 16"]
        path.[d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"]
      h1.float-start= @user.name

  = link_to '編集', edit_user_path(@user), class: 'btn btn-link btn-lg ms-4'


h2.mt-3 貸し出し履歴

table.table.table-hover
  thead.thead-default
    tr
      th= Book.human_attribute_name(:title)
      th= Rental.human_attribute_name(:created_at)
      th= Rental.human_attribute_name(:returned_at)
  tbody
    - @rentals.each do |rental|
      tr
        td= link_to rental.book.title, book_path(rental.book)
        td= I18n.l(rental.created_at)
        - if rental.going?
          td= '貸し出し中'
        - else
          td= I18n.l(rental.returned_at)

- if @user.in_office?
  = form_with url: user_path(in_office: false), method: :patch do |f|
    = f.submit '退職', class: 'btn btn-danger btn-lg col-3 my-5'
- else
  = form_with url: user_path(in_office: true), method: :patch do |f|
    = f.submit '復職', class: 'btn btn-success btn-lg col-3 my-5'